### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by muchai-mercy**
Contribution #Update Dockerfile

### Chore:
- [ ] Update installation packages

### CODE REVIEW

**Review by shemogumbe — COMMENTED** [review]
I see no issue with the dockerfile, but would ask, 
1. what is the reason behind the circleCI tests failing
2. Should we have a whole section in the read me that says, in order to run with docker, create a docker file with the configuration here in instead of just jumping into the file

**Review by shemogumbe — CHANGES_REQUESTED** [review]
From this Dockerfile, is there provision for:
1. Database configuration
2. Solr installation and addition to the configs
3. Tomcat installation and config , for this container

**Comment by muchai-mercy** [comment]
@shemogumbe There are no tests in this repo, no test command either, so the CI integration is not required until we possibly have the ckanext-openafrica code here, which we can then test. 
But the tests build through docker, that is why the Dockerfile update is necessary.

**Comment by muchai-mercy** [comment]
On **Database Configuration**, **Solr** and **Apache**
One will need the ckan instance set up for them to use this repo/codebase. If they already have it, the **Dockerfile** is sufficient.
If not: 
I will update it to take changes that include installation of ckan source using docker

**Review by shemogumbe — COMMENTED** [review]
One of the commands run is cloning the repo, this implies we should not assume it has been set up already, I guesse since we are using this for development and deployment, the container should be 'shipment ready' without expecting that certain things have been done already in the host  machine.
Your argument here implies that you clone the repo and do some configurations on your own, then docker will do others , why not all?

**Comment by muchai-mercy** [comment]
Working on having the dockerfile handle all

**Comment by muchai-mercy** [comment]
@shemogumbe Created a docker-compose.yml file to create containers for the db, solr and redis vs apache-tomcat. Review to confirm one sets up a ckan instance with the one command.

**Review by shemogumbe — APPROVED** [review]

**Review by shemogumbe — APPROVED** [review]

**Pull request merged**
